### ISSUE TITLE
Issues with Neos 3.3

### ISSUE THREAD

**Issue by jobee** [t3n/neos-debug#9]
Is this package supposed to work properly with Neos 3.3 / Php 7.2 ?
After requiring the package via composer, I get this error on cache warmup:

```
./flow flow:cache:warmup
The object "Doctrine\ORM\EntityManagerInterface" which was specified as a property in the object configuration of object "t3n\Neos\Debug\Aspect\CollectDebugInformationAspect" (automatically registered class) does not exist.
Check for spelling mistakes and if that dependency is correctly
configured.
...
```

By clicking through my installation I noticed that the mentioned class actually does exist, any idea what's happening here?

**Comment by jobee** [comment]
**Problem**
`EntityManagerInterface` is not yet configured for injection in Neos 3.3
=> see `Packages/Framework/Neos.Flow/Configuration/Objects.yaml`

**Workaround - that works for me (except SQL queries debugging)**
Add the "missing" injection configuration via an `Configuration/Objects.yaml` file, like
```yaml
# Configuration/Objects.yaml
Doctrine\ORM\EntityManagerInterface:
  scope: singleton
  factoryObjectName: Neos\Flow\Persistence\Doctrine\EntityManagerFactory
```
